a = input("Enter number 1: ")
b = input("Enter number 2: ")
c = input("Enter number 3: ")
d = input("Enter number 4: ")
e = input("Enter number 5: ")
f = input("Enter number 6: ")
g = input("Enter number 7: ")
h = input("Enter number 8: ")
i = input("Enter number 9: ")

print(h + " " + a + " " + f + " ")
print(c + " " + e + " " + g + " ")
print(d + " " + i + " " + b + " ")
